apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  namespace: achat-app
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: dockerdockerdhia/achat_back_prod
        resources:
          limits:
            memory: "800Mi"
            cpu: "0.4"
          requests:
            memory: "600Mi"
            cpu: "0.2"
        ports:
        - containerPort: 8089
        env:
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: db-secrets 
              key: user-username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user-password
        - name: MYSQL_HOST  
          valueFrom: 
            configMapKeyRef:
              name: db-cm
              key: db-host
        - name: MYSQL_DBNAME  
          valueFrom:
            configMapKeyRef:
              name: db-cm 
              key: db-name

---

apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: achat-app
spec:
  selector:
    app: spring-app  
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089



